---
iam_prefix: ""
execution_role: "{{ iam_prefix }}-{{ program }}-{{ tier }}-{{ project_name }}-ecs-task-execution-role"
task_role: "{{ iam_prefix }}-{{ program }}-{{ tier }}-{{ project_name }}-ecs-task-role"
