- name: copy script files
  copy:
    src: ./
    dest: ./scripts/
    directory_mode:

- name: update requirements
  command: "pip install -r scripts/requirements.txt"

- name: update monitors
  command: "python3 scripts/monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}"

- name: update dashboards
  script: dashboards/add_tier_dashboards.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }}