
- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: requirements.txt

- name: update monitors
  script: monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}

- name: update dashboards
  script: dashboards/add_tier_dashboards.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }}