- name: copy requirements file
  copy:
    src: ./
    dest: ./scripts/
    directory_mode:

- name: show directory
  command: "ls"
  register: dir_out

- name: show output
  debug: var={{item}}
  with_items: dir_out.stdout_lines

#- name: Install specified python requirements
#  ansible.builtin.pip:
#    requirements: ./requirements.txt

- name: update requirements
  command: "pip install -r scripts/requirements.txt"

- name: update monitors
#  ansible.builtin.script: scripts/monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}
#  args:
#    executable: python3
#  script: ./monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}
  command: "python3 scripts/monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}"

- name: update dashboards
  script: dashboards/add_tier_dashboards.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }}