- name: copy all files
  copy:
    src: .
    dest: /scripts/

- name: show scripts directory
  command: "ls scripts"
  register: dir_out

- name: show output
  debug: var={{item}}
  with_items: dir_out.stdout_lines

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: files/requirements.txt

- name: update monitors
  script: monitor_update.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }} -l {{ private_location_id }}

- name: update dashboards
  script: dashboards/add_tier_dashboards.py -p {{ project }} -t {{ tier }} -k {{ newrelic_key }}