---
- name: Check if tmp directory exist
  stat:
    path: "{{ workspace }}/tmp"
  register: stat_result

- name: Check if tmp {{ s3_folder }} exist
  stat:
    path: "{{ workspace }}/{{ s3_folder }}"
  register: s3folder_result

- name: remove the tmp if exists
  file:
    path: "{{ workspace }}/tmp"
    state: absent
  when: stat_result.stat.exists

- name: remove the {{ s3_folder }} if exists
  file:
    path: "{{ workspace }}/{{ s3_folder }}"
    state: absent
  when: stat_result.stat.exists

- name: update settings
  template:
    dest: "{{ workspace }}/dataloader/config/config_s3.yml"
    src: "{{ workspace }}/dataloader/config/config.yml.j2"

- name: pip install requirements
  pip:
    requirements: "{{ workspace }}/dataloader/requirements.txt"
    executable: pip3


- name: loader data
  shell:
    cmd: >
      python3
      loader.py 
      config/config_s3.yml
    chdir: "{{ workspace }}/dataloader"
  register: data_loader

- name: show dataloader output
  debug:
    msg: "{{ data_loader }}"