---

- name: copy opensearch restore script
  copy:
    src: opensearch-restore.py
    dest: "{{workspace}}/opensearch-restore.py"
    mode: 0755

- name: load data
  shell:
    cmd: >
      python3 {{workspace}}/opensearch-restore.py --oshost {{opensearch_host}} --repo {{snapshot_repo}} --snapshot {{snapshot_value}}  --s3bucket {{s3_bucket}} --indices {{indices}} --rolearn {{role_arn}} --basepath {{base_path}} --region {{region}}
  register: data_loader

- name: show dataloader output
  debug:
    msg: "{{ data_loader }}"
