############################################################################################################################
#     Backend Build
############################################################################################################################

- name: remove the application_example.properties file
  file:
    path: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/application_example.properties"
    state: absent

- name: copy application.properties file to /src/main/resources/
  template:
    src: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/application.properties.j2"
    dest: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/application.properties"

- name: create graphql directory in backend
  file:
    state: directory
    path: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/graphql"

- name: create yaml directory in backend
  file:
    state: directory
    path: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/yaml"

- name: copy schema from frontend to resources
  template:
    remote_src: yes
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  loop:
    - { src: "{{ workspace }}/{{ project_name }}-frontend/graphql/{{ schema_file}}",dest: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/graphql/{{ schema_file}}"}
    #- { src: "{{ workspace }}/{{ project_name }}-frontend/graphql/{{ public_schema_file}}",dest: "{{ workspace }}/src/main/resources/graphql/{{ public_schema_file}}"}

- name: verify test queries file exists
  stat:
    path: "{{ workspace }}/{{ project_name }}-frontend/yaml/{{ test_queries_file }}"
  register: test_queries

- name: copy test queries from frontend to resources
  template:
    remote_src: yes
    src: "{{ workspace }}/{{ project_name }}-frontend/yaml/{{ test_queries_file }}"
    dest: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/yaml/{{ test_queries_file }}"
  when: test_queries.stat.exists

- name: build springboot code
  #command: /usr/local/maven/bin/mvn package -DskipTests
  command: mvn package -DskipTests
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-11-openjdk
  args:
    chdir: "{{ workspace }/{{ project_name }}-backend"

- name: copy Bento-0.0.1.war to ROOT.war
  copy:
    remote_src: yes
    src: "{{ workspace }}/{{ project_name }}-backend/target/Bento-0.0.1.war"
    dest: "{{ workspace }}/{{ project_name }}-backend/target/ROOT.war"

- name: build {{program}}-{{ project_name }}-{{ container_name }} image
  community.docker.docker_image:
    build:
      args:
        ECR_REPO: "{{ container_registry_url }}"
        PROJECT: "{{ project_name }}"
      path: "{{ workspace }}/{{ project_name }}-backend"
      dockerfile: "{{ dockerfile_path }}"
      pull: yes
      nocache: yes
    name: "{{program}}-{{ project_name }}-{{ container_name }}"
    tag: "{{ image_version }}.{{ build_number }}"
    push: no
    force_source: yes
    source: build

- name: test image for vulnerabilities
  block:
    - name: run trivy scanner on {{program}}-{{ project_name }}-{{ container_name }}:{{ image_version }}-{{ build_number }}
      #command: "trivy image --exit-code 1 --severity HIGH,CRITICAL {{ project_name }}-{{ container_name }}:{{ image_version }}-{{ build_number }}"
      command: "trivy image --severity HIGH,CRITICAL {{program}}-{{ project_name }}-{{ container_name }}:{{ image_version }}.{{ build_number }}"
      register: vuln_results
  always:
    - name: echo vulnerability results
      debug:
        msg: "{{ vuln_results.stdout_lines }}"

- name: Add {{program}}-{{ project_name }}-{{ container_name }} image to ECR
  docker_image:
    name: "{{program}}-{{ project_name }}-{{ container_name }}"
    repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}"
    tag: "{{ image_version }}.{{ build_number }}"
    force_tag: yes
    push: yes
    source: local

- name: Add tag latest to {{program}}-{{ project_name }}-{{ container_name }} image
  community.docker.docker_image:
    name: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}:{{ image_version }}.{{build_number}}"
    repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}:latest"
    force_tag: yes
    push: yes
    source: local
