---
- name: read in deployments file
  uri:
    url: "https://raw.githubusercontent.com/CBIIT/icdc-deployments/{{ tier }}/deployments.yaml"
    return_content: yes
  register: deployments_yaml

- name: decode yaml
  set_fact:
    yaml_list: "{{ deployments_yaml.content | from_yaml }}"

- name: set be_branch
  set_fact:
    be_branch: "{{ yaml_list.services.backend.version | regex_search(_regex) }}"
  vars:
    _regex: '.*(?=\.)'

- name: get model file1
  get_url:
    url: "{{ modelRepo }}/master/model-desc/{{ model_file1_name }}"
    dest: "{{ workspace }}/{{ model_file1 }}"

- name: get model file2
  get_url:
    url: "{{ modelRepo }}/master/model-desc/{{ model_file2_name }}"
    dest: "{{ workspace }}/{{ model_file2 }}"

- name: get about file
  get_url:
    url: "{{ about_file_url[tier] }}"
    dest: "{{ workspace }}/{{ about_file }}"

- name: get indices file
  get_url:
    url: "{{ backendRepo }}/{{ be_branch }}/src/main/resources/yaml/{{ indices_file_name }}"
    dest: "{{ workspace }}/{{ indices_file }}"

- name: update server config file
  template:
    dest: "{{ workspace }}/config/es_loader.yml"
    src: "{{ workspace }}/config/es_loader.yml.j2"

- name: pip install requirements
  pip:
    requirements: "{{ workspace }}/requirements.txt"
    executable: pip3

- name: load data
  shell:
    cmd: >
      python3 es_loader.py {{ indices_file }} {{workspace}}/config/es_loader.yml
    chdir: "{{ workspace }}"
  register: data_loader

- name: show dataloader output
  debug:
    msg: "{{ data_loader }}"
