############################################################################################################################
#     Backend Build
############################################################################################################################

- name: copy application.properties file to /src/main/resources/
  template:
    src: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/application.properties.j2"
    dest: "{{ workspace }}/{{ project_name }}-backend/src/main/resources/application.properties"

- name: build springboot code
  #command: /usr/local/maven/bin/mvn package -DskipTests
  command: mvn package -DskipTests
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-11-openjdk
  args:
    chdir: "{{ workspace }}/{{ project_name }}-backend"

- name: copy Bento-0.0.1.war to ROOT.war
  copy:
    remote_src: yes
    src: "{{ workspace }}/{{ project_name }}-backend/target/Bento-0.0.1.war"
    dest: "{{ workspace }}/{{ project_name }}-backend/target/ROOT.war"

- name: build {{program}}-{{ project_name }}-{{ container_name }} image
  community.docker.docker_image:
    build:
      args:
        ECR_REPO: "{{ container_registry_url }}"
        PROJECT: "{{ project_name }}"
      path: "{{ workspace }}/{{ project_name }}-backend"
      dockerfile: "{{ dockerfile_path }}"
      pull: yes
      nocache: yes
    name: "{{program}}-{{ project_name }}-{{ container_name }}"
    tag: "{{ image_version }}.{{ build_number }}"
    push: no
    force_source: yes
    source: build

- name: Add {{program}}-{{ project_name }}-{{ container_name }} image to ECR
  docker_image:
    name: "{{program}}-{{ project_name }}-{{ container_name }}"
    repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}"
    tag: "{{ image_version }}.{{ build_number }}"
    force_tag: yes
    push: yes
    source: local

- name: Add tag latest to {{program}}-{{ project_name }}-{{ container_name }} image
  community.docker.docker_image:
    name: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}:{{ image_version }}.{{build_number}}"
    repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ container_name }}:latest"
    force_tag: yes
    push: yes
    source: local
