name: TFLint
on: [pull_request]
jobs:
  tflint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/modules/opensearch/examples
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: |
          terraform init

      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: "true"
          filter_mode: "file" 
          flags: "--module"
          